version: '3.8'

services:
  db:
    image: postgres:15 # Or your preferred version
    container_name: djanmongo_postgres_db
    environment:
      POSTGRES_DB: djanmongo_dev
      POSTGRES_USER: djanmongo_user
      POSTGRES_PASSWORD: djanmongo_password # Use a stronger password in production/secrets management
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432 to avoid conflicts if you have postgres locally

volumes:
  postgres_data: 