# Generated by Django 5.1.7 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_attack_effort_remove_battle_player1_action_and_more'),
        ('users', '0002_user_selected_attacks_alter_user_attacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='selected_attacks',
        ),
        migrations.AlterField(
            model_name='user',
            name='attacks',
            field=models.ManyToManyField(blank=True, related_name='users', to='game.attack'),
        ),
    ]
