# Generated by Django 5.1.7 on 2025-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_attack_effort_remove_battle_player1_action_and_more'),
        ('users', '0003_remove_user_selected_attacks_alter_user_attacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_attacks',
            field=models.ManyToManyField(blank=True, related_name='selected_by_users', to='game.attack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attack',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='attacks',
            field=models.ManyToManyField(blank=True, related_name='learned_by_users', to='game.attack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='defense',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='speed',
            field=models.IntegerField(default=5),
        ),
    ]
