# Generated by Django 5.1.7 on 2025-04-09 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_max_hp_user_selected_attacks_alter_user_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the user made an authenticated request.'),
        ),
    ]
