# Generated by Django 5.1.7 on 2025-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booster_credits',
            field=models.PositiveIntegerField(default=0, help_text='Currency earned from battles to open boosters.'),
        ),
    ]
