# Generated by Django 5.1.7 on 2025-04-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_difficulty_user_is_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_hp',
        ),
    ]
