# Generated by Django 5.1.7 on 2025-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_max_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='user',
            name='allow_bot_challenges',
            field=models.BooleanField(default=False, help_text='Allows other users to initiate a battle against this user controlled by AI.'),
        ),
    ]
