# Generated by Django 5.1.7 on 2025-04-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_difficulty_remove_user_is_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attack',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='defense',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='speed',
            field=models.IntegerField(default=100),
        ),
    ]
