# Generated by Django 5.1.7 on 2025-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_attack_alter_user_defense_alter_user_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stats',
            field=models.JSONField(default=dict, help_text='Stores battle statistics like wins/losses vs human/bot, damage dealt etc.'),
        ),
    ]
