# Generated by Django 5.1.7 on 2025-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_prompt',
            field=models.TextField(blank=True, help_text='The prompt used to generate the current profile picture.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL of the generated profile picture.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='booster_credits',
            field=models.PositiveIntegerField(default=100, help_text='Currency earned from battles to open boosters.'),
        ),
    ]
