# Generated by Django 5.1.7 on 2025-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_profile_picture_prompt_user_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded string of the generated profile picture.', null=True),
        ),
    ]
