# Generated by Django 5.1.7 on 2025-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(choices=[('self', 'Self'), ('enemy', 'Enemy')], default='enemy', max_length=5)),
                ('hp_amount', models.IntegerField(default=0, help_text='Damage (negative value) or Heal (positive value)')),
                ('target_stat', models.CharField(choices=[('ATK', 'Attack'), ('DEF', 'Defense'), ('SPEED', 'Speed'), ('HP', 'HP'), ('NONE', 'None')], default='NONE', max_length=5)),
                ('stat_mod', models.IntegerField(default=0, help_text='Number of stages to modify stat (+/-)')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('current_hp_player1', models.IntegerField(blank=True, null=True)),
                ('current_hp_player2', models.IntegerField(blank=True, null=True)),
                ('stat_stages_player1', models.JSONField(default=dict)),
                ('stat_stages_player2', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
