# Generated by Django 5.1.7 on 2025-04-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='power',
            field=models.PositiveIntegerField(default=0, help_text='Base power of the attack (0 for non-damaging moves)'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='hp_amount',
            field=models.IntegerField(default=0, help_text='Direct HP change (e.g., healing, recoil). Usually 0 for damaging moves.'),
        ),
    ]
