# Generated by Django 5.1.7 on 2025-04-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_attack_power_alter_attack_hp_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='last_turn_summary',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
