# Generated by Django 5.1.7 on 2025-04-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_battle_last_turn_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
