# Generated by Django 5.1.7 on 2025-04-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_battle_turn_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='turn_count',
        ),
    ]
