# Generated by Django 5.1.7 on 2025-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_battle_turn_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='emoji',
            field=models.CharField(blank=True, help_text='Optional emoji icon for the attack', max_length=5, null=True),
        ),
    ]
