# Generated by Django 5.1.7 on 2025-04-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_attack_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='effort',
            field=models.IntegerField(default=0, help_text='How much effort this attack costs the user to use'),
        ),
    ]
