# Generated by Django 5.1.7 on 2025-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_attack_effort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player1_action',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player2_action',
        ),
        migrations.AddField(
            model_name='attack',
            name='momentum_cost',
            field=models.PositiveIntegerField(default=1, help_text='Momentum generated by using this attack'),
        ),
        migrations.AddField(
            model_name='battle',
            name='current_momentum_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='current_momentum_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='whose_turn',
            field=models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], default='player1', max_length=10),
        ),
    ]
