# Generated by Django 5.1.7 on 2025-04-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_attack_lua_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player1_state',
            field=models.JSONField(default=dict, help_text='Stores ongoing effects like DOTs, statuses, counters for Player 1'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_state',
            field=models.JSONField(default=dict, help_text='Stores ongoing effects like DOTs, statuses, counters for Player 2'),
        ),
    ]
