# Generated by Django 5.1.7 on 2025-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_battle_player1_state_battle_player2_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='lua_script',
        ),
        migrations.AddField(
            model_name='attack',
            name='lua_script_after_action',
            field=models.TextField(blank=True, help_text="Lua script intended to be registered via register_hook('after_action', ATTACK_ID).\nRuns AFTER each player's action phase (including script/std effects) if registered, but before end-of-turn effects.", null=True, verbose_name='After Action Hook Script'),
        ),
        migrations.AddField(
            model_name='attack',
            name='lua_script_before_action',
            field=models.TextField(blank=True, help_text="Lua script intended to be registered via register_hook('before_action', ATTACK_ID).\nRuns BEFORE each player's action phase if registered.", null=True, verbose_name='Before Action Hook Script'),
        ),
        migrations.AddField(
            model_name='attack',
            name='lua_script_on_use',
            field=models.TextField(blank=True, help_text='Lua script executed immediately when this attack is used.\nCan use API functions to apply effects, modify state, and register/unregister hooks.', null=True, verbose_name='On Use Script'),
        ),
    ]
