# Generated by Django 5.1.7 on 2025-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_attack_lua_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='lua_script_after_action',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='lua_script_before_action',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='lua_script_on_use',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player1_state',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player2_state',
        ),
        migrations.AddField(
            model_name='attack',
            name='lua_script',
            field=models.TextField(blank=True, help_text="Optional Lua script for custom attack effects. \nAvailable functions: log(msg), get_hp(role), set_hp(role, val), get_stat_stage(role, stat), set_stat_stage(role, stat, val), get_momentum(role), set_momentum(role, val), chance(probability). \nRoles: 'attacker', 'target'. Stats: 'attack', 'defense', 'speed'.Reads from context: ATTACKER_HP, TARGET_HP, DAMAGE_DEALT (if applicable).", null=True),
        ),
    ]
