# Generated by Django 5.1.7 on 2025-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_attack_lua_script_after_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='lua_script',
        ),
        migrations.AddField(
            model_name='battle',
            name='custom_statuses_player1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='custom_statuses_player2',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
