# Generated by Django 5.1.7 on 2025-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_attack_hp_amount_remove_attack_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='custom_statuses_player1',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='custom_statuses_player2',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
