# Generated by Django 5.1.7 on 2025-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_battle_custom_statuses_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='lua_script_on_targeted',
            field=models.TextField(blank=True, help_text="Lua script to potentially register. Runs when the script's target is targeted by an opponent's attack (before the opponent's main attack script runs).", null=True, verbose_name='On Targeted Script'),
        ),
        migrations.AddField(
            model_name='attack',
            name='register_on_targeted',
            field=models.BooleanField(default=False, help_text="If checked, the 'On Targeted Script' will be registered against the user when this attack is used.", verbose_name="Register 'On Targeted' Script?"),
        ),
    ]
