# Generated by Django 5.1.7 on 2025-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_attack_lua_script_on_targeted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for identifying the script in admin.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what the script does.')),
                ('lua_code', models.TextField(help_text='The actual Lua script content.', verbose_name='Lua Code')),
                ('trigger_on_attack', models.BooleanField(default=False, help_text='Runs once immediately when the associated Attack is used.', verbose_name='Trigger On Attack Use?')),
                ('trigger_before_attacker_turn', models.BooleanField(default=False, help_text='If persistent, runs before the original attacker takes their turn.', verbose_name='Trigger Before Attacker Turn?')),
                ('trigger_after_attacker_turn', models.BooleanField(default=False, help_text='If persistent, runs after the original attacker finishes their turn.', verbose_name='Trigger After Attacker Turn?')),
                ('trigger_before_target_turn', models.BooleanField(default=False, help_text='If persistent, runs before the original target takes their turn.', verbose_name='Trigger Before Target Turn?')),
                ('trigger_after_target_turn', models.BooleanField(default=False, help_text='If persistent, runs after the original target finishes their turn.', verbose_name='Trigger After Target Turn?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attack',
            name='lua_script_after_opponent',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='lua_script_before_opponent',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='lua_script_on_attack',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='register_after_opponent',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='register_before_opponent',
        ),
        migrations.AlterField(
            model_name='battle',
            name='registered_scripts',
            field=models.JSONField(blank=True, default=list, verbose_name='Active Script Instances'),
        ),
        migrations.AddField(
            model_name='attack',
            name='scripts',
            field=models.ManyToManyField(blank=True, related_name='attacks', to='game.script'),
        ),
    ]
