# Generated by Django 5.1.7 on 2025-04-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_script_remove_attack_lua_script_after_opponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='scripts',
        ),
        migrations.AddField(
            model_name='script',
            name='attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='game.attack'),
        ),
    ]
