# Generated by Django 5.1.7 on 2025-04-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_script_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='attack',
            field=models.ForeignKey(help_text='The Attack this script is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='game.attack'),
        ),
    ]
