# Generated by Django 5.1.7 on 2025-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_script_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player1_snapshot_attack_ids',
            field=models.JSONField(blank=True, default=list, help_text="Snapshot of Player 1's selected attack IDs at battle start."),
        ),
        migrations.AddField(
            model_name='battle',
            name='player1_snapshot_stats',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of Player 1's base stats (hp, attack, defense, speed) at battle start."),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_snapshot_attack_ids',
            field=models.JSONField(blank=True, default=list, help_text="Snapshot of Player 2's selected attack IDs at battle start."),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_snapshot_stats',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of Player 2's base stats (hp, attack, defense, speed) at battle start."),
        ),
    ]
