# Generated by Django 5.1.7 on 2025-04-17 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_battle_player1_snapshot_attack_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='player1_snapshot_attack_ids',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player1_snapshot_stats',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player2_snapshot_attack_ids',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player2_snapshot_stats',
        ),
        migrations.AddField(
            model_name='attack',
            name='turn_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='battle',
            name='current_hp_player1',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='battle',
            name='current_hp_player2',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='battle',
            name='custom_statuses_player1',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='battle',
            name='custom_statuses_player2',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='battle',
            name='last_turn_summary',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battle',
            name='registered_scripts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battle',
            name='turn_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='battle',
            name='whose_turn',
            field=models.CharField(blank=True, choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BattlePlayer1AttackSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.attack')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.battle')),
            ],
            options={
                'unique_together': {('battle', 'attack')},
            },
        ),
        migrations.AddField(
            model_name='attack',
            name='battle_attacks_player1',
            field=models.ManyToManyField(blank=True, related_name='battles_as_player1_attack', through='game.BattlePlayer1AttackSelection', to='game.attack'),
        ),
        migrations.CreateModel(
            name='BattlePlayer2AttackSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.attack')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.battle')),
            ],
            options={
                'unique_together': {('battle', 'attack')},
            },
        ),
        migrations.AddField(
            model_name='attack',
            name='battle_attacks_player2',
            field=models.ManyToManyField(blank=True, related_name='battles_as_player2_attack', through='game.BattlePlayer2AttackSelection', to='game.attack'),
        ),
    ]
