# Generated by Django 5.1.7 on 2025-04-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_battle_player1_snapshot_attack_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='battle_attacks_player1',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='battle_attacks_player2',
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_attacks_player1',
            field=models.ManyToManyField(blank=True, related_name='battles_as_player1_attack', through='game.BattlePlayer1AttackSelection', to='game.attack'),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_attacks_player2',
            field=models.ManyToManyField(blank=True, related_name='battles_as_player2_attack', through='game.BattlePlayer2AttackSelection', to='game.attack'),
        ),
    ]
