# Generated by Django 5.1.7 on 2025-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_remove_attack_battle_attacks_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player2_is_ai_controlled',
            field=models.BooleanField(default=False, help_text='True if player 2 is being controlled by AI in this battle.'),
        ),
    ]
