# Generated by Django 5.1.7 on 2025-04-20 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_battle_player2_is_ai_controlled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackUsageStats',
            fields=[
                ('attack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usage_stats', serialize=False, to='game.attack')),
                ('times_used', models.PositiveIntegerField(db_index=True, default=0, help_text='Total times this attack was used in any battle.')),
                ('wins_contributed', models.PositiveIntegerField(db_index=True, default=0, help_text='Total wins in battles where this attack was used by the winner.')),
            ],
        ),
        migrations.RemoveField(
            model_name='attack',
            name='turn_number',
        ),
        migrations.AddField(
            model_name='attack',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who generated this attack.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='player1_attacks_used',
            field=models.ManyToManyField(blank=True, related_name='battles_used_by_player1', to='game.attack'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_attacks_used',
            field=models.ManyToManyField(blank=True, related_name='battles_used_by_player2', to='game.attack'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='momentum_cost',
            field=models.PositiveIntegerField(default=1, help_text='Base momentum cost before speed modification'),
        ),
    ]
