# Generated by Django 5.1.7 on 2025-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_attackusagestats_remove_attack_turn_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_generation_cost', models.PositiveIntegerField(default=1, help_text='The cost in Booster Credits to generate a set of attacks.')),
            ],
            options={
                'verbose_name_plural': 'Game Configuration',
            },
        ),
    ]
