# Generated by Django 5.1.7 on 2025-04-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_gameconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackusagestats',
            name='wins_contributed',
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='co_used_with_counts',
            field=models.JSONField(default=dict, help_text='Counts of other attacks used alongside this one.'),
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='losses_vs_bot',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Losses in battles vs bot opponents where this attack was used by the loser.'),
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='losses_vs_human',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Losses in battles vs human opponents where this attack was used by the loser.'),
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='total_damage_dealt',
            field=models.BigIntegerField(default=0, help_text='Sum of all direct damage dealt by this attack across all uses.'),
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='total_healing_done',
            field=models.BigIntegerField(default=0, help_text='Sum of all direct healing done by this attack across all uses.'),
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='wins_vs_bot',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Wins in battles vs bot opponents where this attack was used by the winner.'),
        ),
        migrations.AddField(
            model_name='attackusagestats',
            name='wins_vs_human',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Wins in battles vs human opponents where this attack was used by the winner.'),
        ),
    ]
