# Generated by Django 5.1.7 on 2025-04-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_remove_script_trigger_after_attacker_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='icon_emoji',
            field=models.CharField(blank=True, default='⚙️', help_text='Emoji to represent this script in the UI.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='tooltip_description',
            field=models.CharField(blank=True, help_text='Short description shown on hover in the UI.', max_length=150),
        ),
    ]
