# Generated by Django 5.1.7 on 2025-04-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_script_icon_emoji_script_tooltip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the user marked this attack as a favorite.'),
        ),
    ]
